# Generated by Django 2.0 on 2018-10-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20181029_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_pal', models.CharField(blank=True, max_length=255, null=True)),
                ('ccn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Credit Card Number')),
                ('ccv', models.CharField(blank=True, max_length=3, null=True, verbose_name='CCV')),
                ('ced', models.CharField(blank=True, max_length=3, null=True, verbose_name='Expiration date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.User')),
            ],
            options={
                'verbose_name_plural': 'Payment methods',
                'verbose_name': 'Payment method',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.User')),
            ],
            options={
                'verbose_name_plural': 'Sites',
                'verbose_name': 'Site',
            },
        ),
        migrations.CreateModel(
            name='SiteOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site options',
                'verbose_name': 'Site option',
            },
        ),
        migrations.CreateModel(
            name='SiteOptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(choices=[('boolean', 'Boolean'), ('list', 'List')], max_length=255)),
                ('site_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.SiteOption')),
            ],
            options={
                'verbose_name_plural': 'Site options',
                'verbose_name': 'Site option',
            },
        ),
        migrations.CreateModel(
            name='WithdrawMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.CharField(blank=True, max_length=255, null=True)),
                ('SWIFT', models.CharField(blank=True, max_length=255, null=True, verbose_name='Credit Card Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.User')),
            ],
            options={
                'verbose_name_plural': 'Withdraw methods',
                'verbose_name': 'Withdraw method',
            },
        ),
    ]
