# Generated by Django 2.0 on 2018-10-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_reservation_sitetags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site types',
                'verbose_name': 'Site type',
            },
        ),
        migrations.RenameModel(
            old_name='SiteTags',
            new_name='SiteTag',
        ),
        migrations.RemoveField(
            model_name='siteoptionitem',
            name='site_option',
        ),
        migrations.AddField(
            model_name='site',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='manager.SiteTag'),
        ),
        migrations.DeleteModel(
            name='SiteOption',
        ),
        migrations.DeleteModel(
            name='SiteOptionItem',
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manager.SiteType'),
        ),
    ]
